server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: resource-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

com:
  microservices:
    service:
      storage:
        name: storage-service

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

resilience4j:
  circuitbreaker:
    instances:
      storage-service-client:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 5s
        permittedNumberOfCallsInHalfOpenState: 10
        maxWaitDurationInHalfOpenState: 1s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 1
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: false
        writableStackTraceEnabled: true
        recordExceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException

s3:
  region: eu-central-1

eureka:
  instance:
    prefer-ip-address: false
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: trace_id=%mdc{trace_id:-0} %5p
