server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: resource-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

s3:
  region: eu-central-1
  bucket: resources

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        web: debug
