spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resource-service-db
    username: postgres
    password: postgres

com:
  microservices:
    service:
      api-gateway:
        url: http://localhost:8090

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

s3:
  endpoint-uri: http://localhost:4566

kafka:
  bootstrap-address: localhost:9093
  topic: resource-upload
