spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/storage-service-db
    username: postgres
    password: postgres

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

keycloak:
  auth-server-url: http://localhost:8100