spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/song-service-db
    username: postgres
    password: postgres

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
